module cli

// make_commands.v - Code Generation Commands (Laravel artisan make: inspired)
//
// Provides stub generators for quickly scaffolding Photon components:
//   make:command      - generate a CLI command
//   make:controller   - generate a web controller
//   make:middleware   - generate a middleware
//   make:provider     - generate a service provider
//   make:entity       - generate an ORM entity
//   make:repository   - generate a repository
//   make:job          - generate a queue job
//   make:migration    - generate a database migration

import os

// MakeCommandCommand generates a new CLI command file
pub struct MakeCommandCommand {
	BaseCommand
}

pub fn new_make_command_command() &MakeCommandCommand {
	return &MakeCommandCommand{
		BaseCommand: BaseCommand{
			name: 'make:command'
			description: 'Generate a new CLI command class'
			sig: '<name>'
		}
	}
}

pub fn (c &MakeCommandCommand) execute(input &CommandInput, output &CommandOutput) ! {
	name := input.get_arg(0)
	if name.len == 0 {
		return error('command name is required. Usage: make:command <Name>')
	}

	stub := generate_command_stub(name)
	write_stub(name, 'commands', stub, output)!
	return
}

// MakeControllerCommand generates a new web controller
pub struct MakeControllerCommand {
	BaseCommand
}

pub fn new_make_controller_command() &MakeControllerCommand {
	return &MakeControllerCommand{
		BaseCommand: BaseCommand{
			name: 'make:controller'
			description: 'Generate a new web controller class'
			sig: '<name> [--resource]'
		}
	}
}

pub fn (c &MakeControllerCommand) execute(input &CommandInput, output &CommandOutput) ! {
	name := input.get_arg(0)
	if name.len == 0 {
		return error('controller name is required. Usage: make:controller <Name>')
	}

	is_resource := input.has_flag('resource')
	stub := generate_controller_stub(name, is_resource)
	write_stub(name, 'controllers', stub, output)!
	return
}

// MakeMiddlewareCommand generates a new middleware
pub struct MakeMiddlewareCommand {
	BaseCommand
}

pub fn new_make_middleware_command() &MakeMiddlewareCommand {
	return &MakeMiddlewareCommand{
		BaseCommand: BaseCommand{
			name: 'make:middleware'
			description: 'Generate a new middleware class'
			sig: '<name>'
		}
	}
}

pub fn (c &MakeMiddlewareCommand) execute(input &CommandInput, output &CommandOutput) ! {
	name := input.get_arg(0)
	if name.len == 0 {
		return error('middleware name is required. Usage: make:middleware <Name>')
	}

	stub := generate_middleware_stub(name)
	write_stub(name, 'middleware', stub, output)!
	return
}

// MakeProviderCommand generates a new service provider
pub struct MakeProviderCommand {
	BaseCommand
}

pub fn new_make_provider_command() &MakeProviderCommand {
	return &MakeProviderCommand{
		BaseCommand: BaseCommand{
			name: 'make:provider'
			description: 'Generate a new service provider class'
			sig: '<name>'
		}
	}
}

pub fn (c &MakeProviderCommand) execute(input &CommandInput, output &CommandOutput) ! {
	name := input.get_arg(0)
	if name.len == 0 {
		return error('provider name is required. Usage: make:provider <Name>')
	}

	stub := generate_provider_stub(name)
	write_stub(name, 'providers', stub, output)!
	return
}

// MakeEntityCommand generates a new ORM entity
pub struct MakeEntityCommand {
	BaseCommand
}

pub fn new_make_entity_command() &MakeEntityCommand {
	return &MakeEntityCommand{
		BaseCommand: BaseCommand{
			name: 'make:entity'
			description: 'Generate a new entity class'
			sig: '<name>'
		}
	}
}

pub fn (c &MakeEntityCommand) execute(input &CommandInput, output &CommandOutput) ! {
	name := input.get_arg(0)
	if name.len == 0 {
		return error('entity name is required. Usage: make:entity <Name>')
	}

	stub := generate_entity_stub(name)
	write_stub(name, 'entities', stub, output)!
	return
}

// ============================================================
// Stub generators
// ============================================================

fn generate_command_stub(name string) string {
	pascal := to_pascal_case(name)
	snake := to_snake_case(name)
	return 'module commands

import photon.cli

// ${pascal}Command — generated by Photon CLI
pub struct ${pascal}Command {
	cli.BaseCommand
}

pub fn new_${snake}_command() &${pascal}Command {
	return &${pascal}Command{
		BaseCommand: cli.BaseCommand{
			name: \"${snake}\"
			description: \"${pascal} command description\"
			sig: \"[--option=value]\"
		}
	}
}

pub fn (c &${pascal}Command) execute(input &cli.CommandInput, output &cli.CommandOutput) ! {
	output.success(\"${pascal} command executed!\")
	return
}
'
}

fn generate_controller_stub(name string, is_resource bool) string {
	pascal := to_pascal_case(name)
	mut resource_methods := ''
	if is_resource {
		resource_methods = '
// index lists all ${pascal} resources
@[get; \"/${to_snake_case(name)}\"]
pub fn (mut c ${pascal}Controller) index() veb.Result {
	c.set_content_type(\"application/json\")
	return c.text(\"[{\\\"id\\\":1,\\\"name\\\":\\\"${to_snake_case(name)}\\\"}]")
}

// show returns a single ${pascal} resource
@[get; \"/${to_snake_case(name)}/:id\"]
pub fn (mut c ${pascal}Controller) show(id string) veb.Result {
	c.set_content_type(\"application/json\")
	return c.text(\"{\\\"id\\\":\" + id + \",\\\"name\\\":\\\"${to_snake_case(name)}\\\"}\")
}

// store creates a new ${pascal} resource
@[post; \"/${to_snake_case(name)}\"]
pub fn (mut c ${pascal}Controller) store() veb.Result {
	c.set_content_type(\"application/json\")
	return c.text(\"{\\\"status\\\":\\\"created\\\"}\")
}

// update modifies an existing ${pascal} resource
@[put; \"/${to_snake_case(name)}/:id\"]
pub fn (mut c ${pascal}Controller) update(id string) veb.Result {
	c.set_content_type(\"application/json\")
	return c.text(\"{\\\"id\\\":\" + id + \",\\\"status\\\":\\\"updated\\\"}\")
}

// destroy deletes a ${pascal} resource
@[delete; \"/${to_snake_case(name)}/:id\"]
pub fn (mut c ${pascal}Controller) destroy(id string) veb.Result {
	c.set_content_type(\"application/json\")
	return c.text(\"{\\\"id\\\":\" + id + \",\\\"status\\\":\\\"deleted\\\"}\")
}'
	}
	return 'module controllers

import veb

// ${pascal}Controller — generated by Photon CLI
pub struct ${pascal}Controller {
	veb.Context
}
' + resource_methods
}

fn generate_middleware_stub(name string) string {
	pascal := to_pascal_case(name)
	return 'module middleware

import photon.web

// ${pascal}Middleware — generated by Photon CLI
pub fn ${to_snake_case(name)}_middleware(mut ctx &web.MiddlewareContext) !bool {
	// Add middleware logic here
	return true
}
'
}

fn generate_provider_stub(name string) string {
	pascal := to_pascal_case(name)
	snake := to_snake_case(name)
	return 'module providers

import photon.core

// ${pascal}ServiceProvider — generated by Photon CLI
pub struct ${pascal}ServiceProvider {}

pub fn (p &${pascal}ServiceProvider) name() string {
	return \"${snake}\"
}

pub fn (p &${pascal}ServiceProvider) register(app &core.ApplicationContext) ! {
	// Register beans in the container here
}

pub fn (p &${pascal}ServiceProvider) boot(app &core.ApplicationContext) ! {
	// Post-registration boot logic here
}
'
}

fn generate_entity_stub(name string) string {
	pascal := to_pascal_case(name)
	snake := to_snake_case(name)
	table := snake + 's'
	return 'module entities

// ${pascal} — generated by Photon CLI
@[table: \"${table}\"]
pub struct ${pascal} {
pub mut:
	id         int    @[primary_key; sql: \"id\"; sql_type: \"INTEGER\"]
	created_at i64    @[sql: \"created_at\"; sql_type: \"INTEGER\"]
	updated_at i64    @[sql: \"updated_at\"; sql_type: \"INTEGER\"]
}
'
}

// ============================================================
// Helpers
// ============================================================

fn write_stub(name string, dir string, content string, output &CommandOutput) ! {
	path := '${dir}/${to_snake_case(name)}.v'

	// Ensure directory exists
	os.mkdir_all(dir) or {}

	// Write file
	os.write_file(path, content)!

	output.success('Created: ${path}')
}

// to_snake_case converts PascalCase or camelCase to snake_case
fn to_snake_case(s string) string {
	mut result := ''
	for i, ch in s {
		if ch.is_capital() && i > 0 {
			result += '_'
		}
		result += ch.ascii_str().to_lower()
	}
	return result
}

// to_pascal_case converts snake_case to PascalCase
fn to_pascal_case(s string) string {
	mut result := ''
	mut capitalize_next := true
	for ch in s {
		if ch == `_` || ch == `-` {
			capitalize_next = true
			continue
		}
		if capitalize_next {
			result += ch.ascii_str().to_upper()
			capitalize_next = false
		} else {
			result += ch.ascii_str()
		}
	}
	return result
}
