module core

// build_info.v - Build Information (SubTask D7.1)
//
// Provides BuildInfo — a serializable record of how/when/where the
// application binary was built. Mirrors Spring Boot's
// BuildProperties / git.properties / META-INF/build-info.properties.
//
// The info is exposed over HTTP via the /info actuator endpoint
// (see web/actuator_info.v) and is intended for:
//   - Runtime version identification in production
//   - CI/CD traceability (commit SHA → deployed binary)
//   - Debugging "which version is running?" questions without shell access
//
// ── File Format ──
//
// BuildInfo is loaded from a `build.info` file in the working directory
// (or an explicit path). The file uses a simple `key=value` format, one
// per line, with `#` lines treated as comments:
//
//   # build.info — generated by CI
//   version=0.1.0
//   commit=abc123def456
//   commit_time=2026-06-20T10:00:00Z
//   build_time=2026-06-20T10:30:00Z
//   v_version=0.5.1
//
// This format is intentionally compatible with Java .properties files
// (minus escaping) so it can be generated by the same CI steps that
// produce Spring Boot's build-info.properties.
//
// ── Loading Strategy ──
//
// load_build_info() reads from the filesystem at runtime. If the file is
// missing or unreadable, it returns default_build_info() — this keeps the
// /info endpoint usable in development without forcing a build step.
//
// We deliberately avoid V's `$embed_file(...)` because that requires the
// file to exist at compile time, which would break clean builds in dev
// environments where build.info hasn't been generated yet.
import os

// BuildInfo records how/when/where the application was built.
//
// Spring equivalent: org.springframework.boot.info.BuildProperties
pub struct BuildInfo {
pub mut:
	version     string = '0.0.0' // semantic version (e.g. '0.1.0')
	commit      string = 'unknown' // git commit SHA
	commit_time string = 'unknown' // ISO-8601 timestamp of the commit
	build_time  string = 'unknown' // ISO-8601 timestamp of the build
	v_version   string = 'unknown' // V compiler version used to build
}

// default_build_info returns a BuildInfo with all fields set to their
// defaults. Used when no build.info file is available (e.g. dev builds).
pub fn default_build_info() BuildInfo {
	return BuildInfo{}
}

// load_build_info reads build metadata from a `build.info` file at the
// given path. If the file cannot be read (missing, permission denied,
// etc.), default_build_info() is returned — the /info endpoint remains
// usable, just with placeholder values.
//
// The file format is `key=value` per line, with `#` lines as comments.
// Unknown keys are silently ignored so future fields can be added without
// breaking older parsers.
//
// Example file:
//   version=0.1.0
//   commit=abc123
//   build_time=2026-06-20T10:30:00Z
pub fn load_build_info(path string) BuildInfo {
	content := os.read_file(path) or {
		return default_build_info()
	}
	return parse_build_info(content)
}

// parse_build_info parses build.info-formatted content into a BuildInfo.
// Lines starting with `#` are comments; blank lines are skipped.
// Unknown keys are ignored. Malformed lines (no `=`) are skipped.
pub fn parse_build_info(content string) BuildInfo {
	mut info := BuildInfo{}

	for line in content.split_into_lines() {
		trimmed := line.trim_space()
		if trimmed.len == 0 || trimmed.starts_with('#') {
			continue
		}

		eq_idx := trimmed.index('=') or {
			continue
		}
		key := trimmed[..eq_idx].trim_space()
		val := trimmed[eq_idx + 1..].trim_space()

		match key {
			'version' { info.version = val }
			'commit' { info.commit = val }
			'commit_time' { info.commit_time = val }
			'build_time' { info.build_time = val }
			'v_version' { info.v_version = val }
			else {}
		}
	}

	return info
}
