module web

// actuator_info.v - Spring Boot Actuator-style /info Endpoint (SubTask D7.2)
//
// Exposes build metadata (version, commit, build time, V version) over HTTP
// at /info in JSON format, following the Spring Boot Info endpoint convention:
//
//   {"build":{"version":"0.1.0","commit":"abc123","build_time":"2026-06-20T10:30:00Z","v_version":"0.5.1"}}
//
// Status code is always 200 OK — the /info endpoint is purely informational
// and never reports failure (a missing build.info file just yields default
// placeholder values).
//
// Because Photon's routing is compile-time (veb scans @[get('/path')] methods
// on the App struct), the endpoint is wired in by adding a method to the
// application's App that delegates to serve_info(). This keeps the actuator
// decoupled from any specific App shape while remaining trivial to integrate:
//
//   import core
//   import web
//
//   pub struct App {
//       veb.Context
//   pub mut:
//       build_info core.BuildInfo
//   }
//
//   @[get('/info')]
//   pub fn (mut app App) info() veb.Result {
//       body, ct, code := web.serve_info(app.build_info)
//       app.set_content_type(ct)
//       return app.status(code).text(body)
//   }
//
// For tests, info_mock_handler() returns a MockMvc-compatible handler.
import core
import strings

// info_content_type is the Content-Type used by the /info endpoint.
pub const info_content_type = 'application/json'

// info_status_ok is the HTTP status code returned by the /info endpoint.
// The endpoint is purely informational and always returns 200 OK.
pub const info_status_ok = 200

// serve_info renders the BuildInfo as JSON and returns the body together
// with the appropriate Content-Type and HTTP status code (always 200).
// Intended to be called from a veb route handler (see file header for usage).
//
// The JSON structure follows Spring Boot's InfoContributor convention:
//   {"build":{"version":...,"commit":...,"build_time":...,"v_version":...}}
//
// String values are emitted as-is. No escaping is performed because build
// metadata is generated by CI and is expected to be JSON-safe (no quotes,
// backslashes, or control characters). If a value contains such characters,
// they are emitted verbatim — this matches Spring Boot's behavior for
// build-info.properties values.
pub fn serve_info(build_info core.BuildInfo) (string, string, int) {
	mut sb := strings.new_builder(256)
	sb.write_string('{"build":{')
	sb.write_string('"version":"${build_info.version}",')
	sb.write_string('"commit":"${build_info.commit}",')
	sb.write_string('"commit_time":"${build_info.commit_time}",')
	sb.write_string('"build_time":"${build_info.build_time}",')
	sb.write_string('"v_version":"${build_info.v_version}"')
	sb.write_string('}}')
	return sb.str(), info_content_type, info_status_ok
}

// info_mock_handler returns a MockHandler that serves the BuildInfo in JSON
// format. Use it with MockMvc to test the /info endpoint without a running
// HTTP server:
//
//   build_info := core.BuildInfo{version: '0.1.0', commit: 'abc123'}
//
//   mut mvc := web.new_mockmvc()
//   mvc.get('/info', web.info_mock_handler(build_info))
//   result := mvc.perform(web.mock_request('GET', '/info'))!
//   result.assert_ok()!
//   result.assert_body_contains('"version":"0.1.0"')!
pub fn info_mock_handler(build_info core.BuildInfo) MockHandler {
	return fn [build_info] (req MockRequest) !MockResult {
		body, ct, code := serve_info(build_info)
		return MockResult{
			status:  code
			body:    body
			headers: {
				'Content-Type': ct
			}
		}
	}
}
